Configurations:
  - SecurityBase
  - WindowsFeatures
  - NetworkIpConfiguration

WindowsFeatures:
  Name:
    - -Telnet-Client

SecurityBase:
  Role: Baseline

NetworkIpConfiguration:
  Prefix: 24
  Gateway: 192.168.111.50
  DnsServer: 192.168.111.10
  InterfaceAlias: Ethernet
  DisableNetbios: True